# Generated by Django 5.0.2 on 2024-08-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название карточки')),
                ('picture', models.ImageField(null=True, upload_to='img/', verbose_name='Фотография')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='Diploms_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название диплома')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='Текст к диплому')),
                ('picture', models.ImageField(null=True, upload_to='img/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Диплом',
                'verbose_name_plural': 'Дипломы',
            },
        ),
        migrations.CreateModel(
            name='Dostijenia_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название достижения')),
                ('Year', models.CharField(blank=True, max_length=255, verbose_name='Какой год')),
                ('picture', models.ImageField(null=True, upload_to='img/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='DostijeniaSchoolboy_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название достижения')),
                ('Year', models.CharField(blank=True, max_length=255, verbose_name='Какой год')),
                ('picture', models.ImageField(null=True, upload_to='img/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Достижения учащихся',
                'verbose_name_plural': 'Достижения учащихся',
            },
        ),
        migrations.CreateModel(
            name='PhotoGalery_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название фото')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='Текст к фотографии')),
                ('picture', models.ImageField(null=True, upload_to='img/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Фотогалерея',
                'verbose_name_plural': 'Фотогалерея',
            },
        ),
        migrations.CreateModel(
            name='VieoGalery_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название видео')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='Текст к видео')),
                ('file', models.FileField(blank=True, null=True, upload_to='img/')),
            ],
            options={
                'verbose_name': 'Видеогалерея',
                'verbose_name_plural': 'Видеогалерея',
            },
        ),
    ]
